FROM rodrigocaus/python-transformers:3.10-slim-4.29-torch-cpu

RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc \
    && python -m pip install --upgrade pip \
    && pip install --no-cache-dir "transformers[torch]==4.26"
WORKDIR /django-backend
COPY ./requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY ./src ./src

